import React from "react";
import Filter from "./components/Filter";
import Table from "./components/Table";
import Breadcrumbs from "../components/Breadcrumbs";

const items = [
  { href: "/home", label: "Home" },
  { href: "/sales", label: "Sales" },
  { href: "/Bid tool", label: "Bid Tool" },
];

const BidProductSearchResult = {
  result: {
    success: true,
    message: "Products found successfully!",
    code: 200,
  },
  resProducts: [
    {
      totalQtyInStock: 147,
      productWrapper: {
        storage: "512",
        screenSize: "N/A",
        ram: "16",
        projectName: "vAncona",
        productType: "Desktop",
        productModel: "CM-C-VS2690G",
        productLine: "CM-VERITON",
        productId: "01t3X00000OIcWjQAL",
        productFamily: "CM-C-VS2690G",
        partNumber: "DT.VWMET.00R",
        osType: "WNPRC64",
        osCategory: "MS-PRO",
        gpu: "N",
        ean: "4711121251948",
        cpuFamily: "Intel Core i5",
        cpuBrand: "Intel",
        businessUnit: "CM",
        battery: "N/A",
      },
      pricingWrapper: {
        standardDealerPrice: 696.0,
        publicPrice: 727.0,
        promoDealerPrice: 690.0,
        bucket4_DealerPrice: 385.0,
        bucket3_DealerPrice: 580.0,
        bucket2_DealerPrice: 922.0,
        bucket1_DealerPrice: 403.0,
      },
    },
    {
      totalQtyInStock: 136,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "Ganymede_ADU",
        productType: "Notebook",
        productModel: "NU-A515-57G-740H",
        productLine: "NU-ASPIRE",
        productId: "01t3X00000Ibll6QAB",
        productFamily: "NU-A515-57G",
        partNumber: "NX.K2FET.006",
        osType: "WNHPML64",
        osCategory: "MS-CO",
        gpu: "GN18-S5 (MX550)",
        ean: "4711121048869",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "NU",
        battery: "50Wh_150300",
      },
      pricingWrapper: {
        standardDealerPrice: 550.0,
        publicPrice: 305.0,
        promoDealerPrice: 747.0,
        bucket4_DealerPrice: 720.0,
        bucket3_DealerPrice: 422.0,
        bucket2_DealerPrice: 439.0,
        bucket1_DealerPrice: 810.0,
      },
    },
    {
      totalQtyInStock: 114,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "Ganymede_ADU",
        productType: "Notebook",
        productModel: "NU-A515-57G-50LU",
        productLine: "NU-ASPIRE",
        productId: "01t3X00000NzW8YQAV",
        productFamily: "NU-A515-57G",
        partNumber: "NX.K2FET.007",
        osType: "WNHPML64",
        osCategory: "MS-CO",
        gpu: "GN18-S5 (MX550)",
        ean: "4711121374791",
        cpuFamily: "Intel Core i5",
        cpuBrand: "Intel",
        businessUnit: "NU",
        battery: "50Wh_150300",
      },
      pricingWrapper: {
        standardDealerPrice: 513.0,
        publicPrice: 852.0,
        promoDealerPrice: 600.0,
        bucket4_DealerPrice: 959.0,
        bucket3_DealerPrice: 614.0,
        bucket2_DealerPrice: 305.0,
        bucket1_DealerPrice: 1.191,
      },
    },
    {
      totalQtyInStock: 108,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "Iris_TL",
        productType: "Notebook",
        productModel: "NU-A515-56G-76M2",
        productLine: "NU-ASPIRE",
        productId: "01t3X00000NzdOyQAJ",
        productFamily: "NU-A515-56G",
        partNumber: "NX.AT2ET.007",
        osType: "WNHPML64",
        osCategory: "MS-CO",
        gpu: "N18S-G5-A1 (MX450)",
        ean: "4711121459894",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "NU",
        battery: "48Wh_150300",
      },
      pricingWrapper: {
        standardDealerPrice: 760.0,
        publicPrice: 412.0,
        promoDealerPrice: 1.19,
        bucket4_DealerPrice: 1.093,
        bucket3_DealerPrice: 861.0,
        bucket2_DealerPrice: 1.175,
        bucket1_DealerPrice: 556.0,
      },
    },
    {
      totalQtyInStock: 66,
      productWrapper: {
        storage: "512",
        screenSize: "N/A",
        ram: "16",
        projectName: "vAncona",
        productType: "Desktop",
        productModel: "CM-C-VS2690G",
        productLine: "CM-VERITON",
        productId: "01t3X00000OIcWdQAL",
        productFamily: "CM-C-VS2690G",
        partNumber: "DT.VWMET.00U",
        osType: "WNPRC64",
        osCategory: "MS-PRO",
        gpu: "N",
        ean: "4711121251979",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "CM",
        battery: "N/A",
      },
      pricingWrapper: {
        standardDealerPrice: 708.0,
        publicPrice: 467.0,
        promoDealerPrice: 277.0,
        bucket4_DealerPrice: 782.0,
        bucket3_DealerPrice: 734.0,
        bucket2_DealerPrice: 1.043,
        bucket1_DealerPrice: 1.03,
      },
    },
    {
      totalQtyInStock: 61,
      productWrapper: {
        storage: "512",
        screenSize: "N/A",
        ram: "16",
        projectName: "Ape238i",
        productType: "Desktop",
        productModel: "AN-C-C24-1700",
        productLine: "AN-ASPIRE",
        productId: "01t3X00000IbwpGQAR",
        productFamily: "AN-C-C24-1700",
        partNumber: "DQ.BJWET.003",
        osType: "WNHPML64",
        osCategory: "MS-CO",
        gpu: "N",
        ean: "4711121116322",
        cpuFamily: "Intel Core i5",
        cpuBrand: "Intel",
        businessUnit: "AN",
        battery: "N/A",
      },
      pricingWrapper: {
        standardDealerPrice: 983.0,
        publicPrice: 1.084,
        promoDealerPrice: 638.0,
        bucket4_DealerPrice: 425.0,
        bucket3_DealerPrice: 574.0,
        bucket2_DealerPrice: 976.0,
        bucket1_DealerPrice: 740.0,
      },
    },
    {
      totalQtyInStock: 59,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "BassDrum_TL",
        productType: "Notebook",
        productModel: "NB-TMP215-53-77WM",
        productLine: "NB-TRAVELMATE",
        productId: "01t3X00000IbM9EQAV",
        productFamily: "NB-TMP215-53",
        partNumber: "NX.VPUET.00R",
        osType: "WNPRC64",
        osCategory: "MS-PRO",
        gpu: "UMA",
        ean: "4710886981435",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "NB",
        battery: "48Wh_150300",
      },
      pricingWrapper: {
        standardDealerPrice: 770.0,
        publicPrice: 357.0,
        promoDealerPrice: 286.0,
        bucket4_DealerPrice: 302.0,
        bucket3_DealerPrice: 1.08,
        bucket2_DealerPrice: 754.0,
        bucket1_DealerPrice: 364.0,
      },
    },
    {
      totalQtyInStock: 58,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "Ganymede_ADU",
        productType: "Notebook",
        productModel: "NU-A515-57G-76N6",
        productLine: "NU-ASPIRE",
        productId: "01t3X00000NzW7uQAF",
        productFamily: "NU-A515-57G",
        partNumber: "NX.K9TET.007",
        osType: "WNHPML64",
        osCategory: "MS-CO",
        gpu: "GN20-S7 (RTX 2050)",
        ean: "4711121374838",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "NU",
        battery: "50Wh_150300",
      },
      pricingWrapper: {
        standardDealerPrice: 1.149,
        publicPrice: 862.0,
        promoDealerPrice: 1.169,
        bucket4_DealerPrice: 737.0,
        bucket3_DealerPrice: 602.0,
        bucket2_DealerPrice: 942.0,
        bucket1_DealerPrice: 1.0,
      },
    },
    {
      totalQtyInStock: 54,
      productWrapper: {
        storage: "512",
        screenSize: "15.6",
        ram: "16",
        projectName: "Scala_TLS",
        productType: "Notebook",
        productModel: "NG-AN515-57-76BF",
        productLine: "NG-GAMING",
        productId: "01t3X00000IaHJdQAN",
        productFamily: "NG-AN515-57",
        partNumber: "NH.QEWET.005",
        osType: "WNHAML64",
        osCategory: "MS-CO",
        gpu: "GN20-E3 (RTX3060)",
        ean: "4710886849308",
        cpuFamily: "Intel Core i7",
        cpuBrand: "Intel",
        businessUnit: "NG",
        battery: "57Wh_190500",
      },
      pricingWrapper: {
        standardDealerPrice: 666.0,
        publicPrice: 545.0,
        promoDealerPrice: 1.014,
        bucket4_DealerPrice: 483.0,
        bucket3_DealerPrice: 859.0,
        bucket2_DealerPrice: 901.0,
        bucket1_DealerPrice: 904.0,
      },
    },
  ],
};

const filterItems = {
  storage: "32#64#128#256#512#1024#1512#2048#3024#4048#5048",
  screenSize: undefined,
  ram: "4#8#16#32#64",
  productType: "Desktop#Monitor#Notebook#Options#Projectors#Tablet",
  osCategory: "Android#Chrome#MS-CO#MS-PRO",
  cpuFamily:
    "AMD Ryzen R3#AMD Ryzen R5#AMD Ryzen R7#Intel Celeron#Intel Core i3#Intel Core i5#Intel Core i7#Intel Core i9#Intel Core U5#Intel Core U7#Intel Core U9#Intel Pentium",
  cpuBrand: "AMD#Intel#Mediatek",
  businessUnit: "AM#AN#CB#CM#CN#DG#DS#EM#MG#MO#MV#NB#NC#NG#NU#OP#PJ#TA#TR",
  minPrice: "25",
  maxPrice: "1240.50",
  minStock: "35",
  maxStock: "1123",
};

const productDetailData = [
  {
    result: {
      success: true,
      message: "Product Tech Specs retrieved successfully!",
      code: 200,
    },
    productWrapper: {
      storage: undefined,
      screenSize: undefined,
      ram: undefined,
      projectName: undefined,
      productType: undefined,
      productModel: undefined,
      productLine: undefined,
      productId: "01t3X00000OIcWjQAL",
      productFamily: undefined,
      partNumber: "DT.VWMET.00R",
      osType: undefined,
      osCategory: undefined,
      gpu: undefined,
      ean: undefined,
      cpuFamily: undefined,
      cpuBrand: undefined,
      businessUnit: undefined,
      battery: undefined,
    },
    availabilityConfig: [
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 63,
        ecpCode: "IT0009054",
        customerName: "Computer Gross S.p.A.",
        accountId: "00120000010yWzaAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 67,
        ecpCode: "IT0009057",
        customerName: "Esprinet",
        accountId: "00120000010yWzeAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 17,
        ecpCode: "IT0018492",
        customerName: "Runner Spa",
        accountId: "00120000010yY5LAAU",
      },
    ],
  },
  {
    result: {
      success: true,
      message: "Product Tech Specs retrieved successfully!",
      code: 200,
    },
    productWrapper: {
      storage: undefined,
      screenSize: undefined,
      ram: undefined,
      projectName: undefined,
      productType: undefined,
      productModel: undefined,
      productLine: undefined,
      productId: "01t3X00000Ibll6QAB",
      productFamily: undefined,
      partNumber: "NX.K2FET.006",
      osType: undefined,
      osCategory: undefined,
      gpu: undefined,
      ean: undefined,
      cpuFamily: undefined,
      cpuBrand: undefined,
      businessUnit: undefined,
      battery: undefined,
    },
    availabilityConfig: [
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 1,
        ecpCode: "IT0009054",
        customerName: "Computer Gross S.p.A.",
        accountId: "00120000010yWzaAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 1,
        ecpCode: "IT0009056",
        customerName: "DATAMATIC SPA",
        accountId: "00120000010yWzcAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 66,
        ecpCode: "IT0009057",
        customerName: "Esprinet",
        accountId: "00120000010yWzeAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 65,
        ecpCode: "IT0009059",
        customerName: "Focelda Spa",
        accountId: "00120000010yWzgAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 3,
        ecpCode: "IT0009062",
        customerName: "Ingram Micro S.r.l.",
        accountId: "00120000010yWziAAE",
      },
    ],
  },
  {
    result: {
      success: true,
      message: "Product Tech Specs retrieved successfully!",
      code: 200,
    },
    productWrapper: {
      storage: undefined,
      screenSize: undefined,
      ram: undefined,
      projectName: undefined,
      productType: undefined,
      productModel: undefined,
      productLine: undefined,
      productId: "01t3X00000NzW8YQAV",
      productFamily: undefined,
      partNumber: "NX.K2FET.007",
      osType: undefined,
      osCategory: undefined,
      gpu: undefined,
      ean: undefined,
      cpuFamily: undefined,
      cpuBrand: undefined,
      businessUnit: undefined,
      battery: undefined,
    },
    availabilityConfig: [
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 73,
        ecpCode: "IT0009051",
        customerName: "Brevi S.p.A.",
        accountId: "00120000010yWzYAAU",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 32,
        ecpCode: "IT0009054",
        customerName: "Computer Gross S.p.A.",
        accountId: "00120000010yWzaAAE",
      },
      {
        price: 439,
        qtyInTransit: 0,
        qtyInStock: 9,
        ecpCode: "IT0009057",
        customerName: "Esprinet",
        accountId: "00120000010yWzeAAE",
      },
    ],
  },
];

export default function Products() {
  return (
    <div className="flex flex-col w-full text-black p-8 pb-20">
      <Breadcrumbs items={items} />
      <div className="flex mt-8 items-start">
        <Filter filterItems={filterItems} />
        <Table
          resProducts={BidProductSearchResult.resProducts}
          productDetailData={productDetailData}
        />
      </div>
    </div>
  );
}
